### ISSUE TITLE
[Bug]: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:[weird symbol here]

### ISSUE THREAD

**Issue by cmwahl** [Fuzss/strawstatues#28] opened 2023-11-11 17:40 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.12

### Notes (Required)

Using this mod on a server with Forge 43.3.0 for Minecraft 1.19.2. There are two players on this server.
1.) Place down the statue
2.) Either one of us tries to change the skin on the statue.
3.) I get "Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:[weird symbol here]"
Only I get kicked and not the other player.

Thank you!

### latest.log (Optional)

https://gist.github.com/cmwahl/57de0e7f145ed7eeb0ab1f04d6e12f6d

**Comment by xhatz** [comment] 2024-03-23 10:33
Hello! Just had this bug in 1.20.1 on a server after setting the skin, disconnected everyone and preventing from logging in again, no error in console.
![image](https://github.com/Fuzss/strawstatues/assets/1364915/904b760b-2f2e-417d-adb5-40f427f312dd)

**Comment by Fuzss** [comment] 2024-03-23 10:40
@xhatz Please send both client and server logs.

**Comment by xhatz** [comment] 2024-03-23 15:14
There were no error log on server but I will try to reproduce and catch client one

**Comment by Fuzss** [comment] 2024-03-23 15:32
Still always send both please, even if you don’t see anything.

**Comment by xhatz** [comment] 2024-03-24 12:31
Hey, sorry for the delay, had to be away yesterday. Here is what I could gather after reproducing the issue (starting server, starting client, logging in, placing straw statue, setting a skin, getting disconnected and closed the game manually).

Client Logs
[latest-client.log](https://github.com/Fuzss/strawstatues/files/14735445/latest-client.log)

Server Logs
[latest-server.log](https://github.com/Fuzss/strawstatues/files/14735449/latest-server.log)

**Comment by Fuzss** [comment] 2024-03-24 14:08
Thanks, fixed in v8.0.3.

The issue is completely separate from the one initially reported though.

**Comment by xhatz** [comment] 2024-03-24 17:34
My bad 😅 I had seen part of the title and the fitting description and error words so I didn't know if I should've done another post. I'll do it next time. Thank you!

**Comment by Fuzss** [comment] 2024-09-21 06:50
#35

**Closed by Fuzss** 2024-09-21 06:50 UTC
Labels: bug
